### ISSUE TITLE
Two plucks in psonic.py

### ISSUE THREAD

**Issue by pageauc** [gkvoelkl/python-sonic#11]
In psonic.py I Just noticed that there are two plucks in the synthesizers. One at line 173 and the other at line 192.  Did a quick check for other dups but could not see any.  
BTW I am still working at sonic-track.  version 0.82 just released.  That is how I found duplicate.
Going to work on saving and reading note data information to/from file(s).  This morning I pointed sonic-track at the TV with sports, news and other channels with motion.  It was quite interesting.  I found that there is a lot of panning in sports so most of the action is near the middle of the screen.  Baseball was good and a weather person was pretty interesting.   I would like to create a video and use some of sonic-track sounds as part of the audio since it tends to sync with the motion.  Just for Fun
Regards Claude.

**Comment by gkvoelkl** [comment]
Thanks. I will do the changes.
