### ISSUE TITLE
Implementation of sample_duration

### ISSUE THREAD

**Issue by wallysalami** [gkvoelkl/python-sonic#14]
Hi, everyone!

I'm planning a Microcontroller 101 course in my university that will use Raspberry Pi. Sonic Pi sounds like a great way to engage students, and this library will help a lot because we have to use Python.

I've been playing with python-sonic for a few days, and I miss one feature from the original API in Ruby: `sample_duration`. That is very handy for drumming loops. Sure, I could give the students a reference table with all the durations, but it would be great if they could just call a function to speed up experimentations.

I'm not familiar with `OscMessageBuilder`, but it seems complicated (or impossible) to get a value back from Sonic Pi. So I was wondering if we can manually add the duration of all samples in the class initializer, and the create a our `sample_duration` function.

```python
#...
LOOP_COMPUS = Sample('loop_compus', 6.486485260770975)
LOOP_AMEN = Sample('loop_amen', 1.753310657596372)
#...

class Sample:
    """
    Sample
    """

    def __init__(self, name, duration):
        self.name = name
        self.duration = duration

def sample_duration(sample):
    return sample.duration

```

How about that? I can write the changes and make a pull request, if you want.

**Comment by gkvoelkl** [comment]
Hi,
great idea. I will integrate it into the main branch.

If there is any public link to your course, I am interested.

Bye Gerhard

**Comment by wallysalami** [comment]
Great! I’ll start coding the changes.

The course will begin in March 2018. There is no webpage so far, but I’ll send you the link when we have one.
