### ISSUE TITLE
Please tell how to run this project

### ISSUE THREAD

**Issue by Alishajabse** [gkvoelkl/python-sonic#19]
I am having problem in running the project even after downloading this project and downloading the SonicPi .
![untitledscreen](https://user-images.githubusercontent.com/37698199/37829195-299e9af2-2ec4-11e8-841f-0cb758a8639a.jpg)
Please tell and guide me how to run the project.

**Comment by MarzioPi** [comment]
Cd into python-sonic-master and then “python setup.py install” after that, if your lucky and no more packets are needed, just write a python program with “from psonic import *” and then execute it as a normal Python program

**Comment by gkvoelkl** [comment]
Or you could install python-sonic 

`pip install python-sonic`

And try the samples in README.rst

First of all you should start sonic pi

**Comment by gkvoelkl** [comment]
If you need any answers

please reopen this
