### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by bennuttall** [gkvoelkl/python-sonic#2]
This is a really great library. Were you planning on packaging it? Would be great to have this available in pip, and later the Raspbian repo (apt-get) Let me know if I can help.

This library works brilliantly with [GPIO Zero](https://github.com/rpi-distro/python-gpiozero), essentially allowing direct Sonic Pi control from GPIO inputs.

Do you have any plans for further development?

Thanks

**Comment by gkvoelkl** [comment]
Thanks for your very nice message.

Yes, I am planning to package for pip. To be part of Raspbian repo would be great. Do you know a good tutorial?

That you use this library together with GPIO Zero is a great idea. Do you have any examples?

My plans for the future? I want to integrate the sound effects (fx) and have a better integration into the Python language. I try to make some examples with Metaprogramming or Decorator.

Ben, you can answer to my email adress: gkvoelkl@nelson-games.de
