### ISSUE TITLE
Intervals in chords seem funny

### ISSUE THREAD

**Issue by dcbb** [gkvoelkl/python-sonic#20]
Am I somehow fundamentally wrong about MIDI notes and chords or are the intervals somewhat off? Minor / major triands look ok, but the the fifths and sevenths worry me... (Sounds off, too.)

     for ctype in [MAJOR, MAJOR7, MINOR, MINOR7]:
	    print(ctype)
	    ns = chord(C4, ctype)
	    for n in ns:
	    	print(n, n - ns[0])
		play(n)
		sleep(0.25)
	 sleep(1)

major
60 0
64 4
71 11
major7
60 0
64 4
71 11
82 22
minor
60 0
63 3
70 10
minor7
60 0
63 3
70 10
80 20

Awesome project by the way. I always thought I'd love to have Python for SonicPi, ever since I discovered it.

**Comment by gkvoelkl** [comment]
C3=60
Eb=63 
E=64 
G=67 
Bb=70 
B=71 
G#=80
Bb=82

I think they are all wrong. I will fix it. 

 major
 60 0
 64 4
 71 11 should be 67
 major7
 60 0
 64 4
  71 11 should be 67
  82 22 should be 70
  minor
  60 0
  63 3
  70 10 should be 67
  minor7
  60 0
  63 3
  70 10 should be 67
  80 20 should be 70

**Comment by Alishajabse** [comment]
ew plsh gimme ewr email id i have a big problem plsh help me plsh plsh plsh
