### ISSUE TITLE
[Feature] Some sort of use_bpm integration

### ISSUE THREAD

**Issue by Zylvian** [gkvoelkl/python-sonic#24]
One of the mains thing I want to use this library for is to control the tempo of a song using a potentiometer, with a visual display.

I know one can set the specific BPM of loops in Sonic Pi by doing something like this:
```ruby
set :bpm , 150

live_loop :kicky do
  use_bpm get(:bpm)
  sample :drum_bass_hard, rate: 1
  sleep 1
end

live_loop :snare_guy do
  use_bpm get(:bpm) #gets 100
  sync :kicky
  sleep 1
  sample :drum_snare_hard, rate: 1
end
```

Would it be hard to integrate that into this library? It would really help!

Note: I tried making this using subprocess and user inputs. It works but it updates pretty slowly. https://hastebin.com/rexavuzepa.py

**Comment by gkvoelkl** [comment]
set_bmp is not possible because all the timing is made in python
