### ISSUE TITLE
Pip install not working

### ISSUE THREAD

**Issue by TeCoEd** [gkvoelkl/python-sonic#3]
Hi

I tried "sudo pip install python-sonic" on my Pi 3 and it fails, states there is no such file.  Any other methods to install your python-sonic? Thanks

**Comment by gkvoelkl** [comment]
Hi,

You can try "sudo pip3 install python-sonic" because it only works with Python 3. Please tell me ich that works.

**Comment by TeCoEd** [comment]
HI
Yes this worked. But I had to remove pip3 first and then reinstall with sudo apt-get install python3-pip
Thanks

Dan Aldred

-------- Original message --------
