### ISSUE TITLE
Rename package so that it complies with packaging standards

### ISSUE THREAD

**Issue by m-roberts** [gkvoelkl/python-sonic#31]
When trying to package this for Debian, the [`source-package-encodes-python-version`](https://lintian.debian.org/tags/source-package-encodes-python-version) package quality check tag is triggered.

> This source package encodes a Python version in its name such as `python2-foo` or `python3-bar`.
>
> This could result in a misleading future situation where this source package supports multiple versions as well unnecessary given that the binary package names will typically encode the supported versions.

If the package were called, for example, `sonic-py`, then the Debian package would be called `python3-sonic-py`, and everything would play nice.

**Comment by m-roberts** [comment]
As an aside, I am happy to provide GitHub Action workflows that will provide automated Debian package builds if you are interested in hosting/managing them yourself.

**Comment by gkvoelkl** [comment]
The name is always the hardest thing.

To change an known name is not so good.

sonic-py is too near to sonic pi
pysonic already exists

python3-python-sonic is not against the debian conventions.

best regards Gerhard
