### ISSUE TITLE
Release latest version (0.4.2) to PyPI

### ISSUE THREAD

**Issue by m-roberts** [gkvoelkl/python-sonic#36]
[This](https://github.com/gkvoelkl/python-sonic/commit/7a31edc065494dfdb4938a49e2cb3c496b130956) commit is yet to make it to PyPI. Can this be released so that `pip install` will work?

**Comment by gkvoelkl** [comment]
I will. But it will last somedays. I am very busy.

**Comment by gkvoelkl** [comment]
PyPi do not accept  the rst file. I think because of the pictures. Now I made a special preadme.txt only for PyPi.
That worked.

**Comment by m-roberts** [comment]
Unfortunately this does not fix my issue, as`PREADME.txt` is not in the source tarball for the release. When the source is downloaded, it cannot be built - `setup.py` does not specify a file that exists.

Replacing `.. code:: ipython3` with `.. code-block:: python` in `README.rst` allows it to be used, so you can delete `PREADME.txt`.

You can also just remove the `long_description_content_type = rst` line, as this is default behaviour.

**Comment by m-roberts** [comment]
What error were you getting when pushing to PyPI?

**Comment by m-roberts** [comment]
Replacing `.. code:: ipython3` with `.. code-block:: python` in `README.rst` allows it to be used, so you can delete PREADME.txt. You can also just remove the `long_description_content_type = rst` line, as this is default behaviour.
